name: global_citizen_game
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_google_wallet: ^0.1.4
  flutter_localizations:
    sdk: flutter
  hydrated_bloc: ^9.1.4
  intl: ^0.18.0
  uuid: ^4.3.3
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  flutter_svg: ^2.0.10+1
  flutter_animate: ^4.5.0
  webview_flutter: ^4.7.0
  flutter_tilt: ^3.0.0
  fl_chart: ^0.66.2

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#4e6d7f"
  adaptive_icon_foreground: "assets/icon/ic_launcher_adaptive_foreground.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - packages/flutter_google_wallet/assets/svg/button/enUS_add_to_google_wallet_wallet-button.svg
    - lib/assets/svg/button/
    - assets/icon/
    - assets/images/
    - assets/images/nav_icons/
    - assets/images/elements/bg/
    - assets/images/elements/icons/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-ExtraBold.ttf
          weight: 800